# Generated by Django 3.2.7 on 2022-03-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220305_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillandcategoryrelation',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='base.skill'),
        ),
        migrations.AlterField(
            model_name='skillandcategoryrelation',
            name='skill_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mtm', to='base.skillcategory'),
        ),
    ]
