# Generated by Django 3.2.7 on 2022-03-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220310_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skill_categories',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_categories',
            field=models.ManyToManyField(blank=True, to='base.SkillCategory'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='base.Skill'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='socials',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='socials',
            field=models.ManyToManyField(blank=True, to='base.Social'),
        ),
    ]
