# Generated by Django 3.2.7 on 2022-03-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_skillandcategoryrelation_blog_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillandcategoryrelation',
            name='blog_topic',
        ),
    ]
