# Generated by Django 3.2.7 on 2022-03-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220310_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills_used',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cv',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
